### PR TITLE
Fixed typo error

### PR DESCRIPTION
**Pull request by lumenCodes**
Changed 'automagically' to 'automatically'.

### CODE REVIEW

**Comment by moppermonster** [comment]
Hi, thank you for your contribution and sorry for replying so slowly. Do you mind if I leave the text as it was? It's supposed to be a  little joke. Let me know if you feel it will seriously confuse people (as it might have done with you) and I'll merge your fix :)

**Comment by lumenCodes** [comment]
Yes, it did confuse me...

**Comment by moppermonster** [comment]
In that case, let the merging commence :)

**Comment by lumenCodes** [comment]
Wow, Thank you

**Pull request merged**
